name: Deploy Infrastructure

on: workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      TF_VAR_vm_admin_password: ${{secrets.TF_VAR_vm_admin_password}}

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Rodar terraform init
        run: terraform init

      - name: Criar plano
        run: terraform plan -destroy -out main.destroy.tfplan
      
      - name: Aplicar plano
        run: terraform apply main.destroy.tfplan